### ISSUE TITLE
Crash on Survey

### ISSUE THREAD

**Issue by SvenSven2009** [mixpanel/mixpanel-iphone#210]
Mixpanel version 2.6.2 application crashes:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UILayoutContainerView mp_snapshotImage]: unrecognized selector sent to instance 0x1703e2a00'
-[Mixpanel presentSurveyWithRootViewController:] (Mixpanel.m:1323)
__43-[Mixpanel showSurveyWithObject:withAlert:]_block_invoke (Mixpanel.m:1371)

If we turn off survey ([Mixpanel sharedInstance].showSurveyOnActive = NO) all good!
In version 2.6.0 also all good.

It is reproduce often on Simulator and iPhone6/iPhone6+ devices

**Comment by alex-hofsteede** [comment]
hi @SvenSven2009 

Does your mixpanel build include the `libMPCategoryHelpers.a` file? That file contains the function that it's crashing on trying to find.

**Comment by SvenSven2009** [comment]
Hi Alex,

I cannot answer to you question because i did rollback to version 2.6.0 and all fine (i am using cocoa pods)

**Comment by SvenSven2009** [comment]
Guys, any updates?
Because, now, in version 2.6.0 we have another crash :https://github.com/mixpanel/mixpanel-iphone/issues/207


All fine if we use ([Mixpanel sharedInstance].showSurveyOnActive = NO) but we need "survey"

**Comment by arittr** [comment]
hey @SvenSven2009 - #207 can be fixed by manually copying the storyboard resource to your main app bundle. take a look at https://github.com/hyperlab/TiMixpanel/issues/4 for detailed instructions - the main issue here is that the Mixpanel library is looking for the XIB in your main app bundle instead of in the pod installed Mixpanel bundle. let me know if this helps!

**Comment by SvenSven2009** [comment]
Hello arittr -    I was added manually storyboards from Mixpanel but, unfortunately, crash still reproduce and reproduce only on iPhone 6 and 6+....And may be it is help:i show UIWindow  after app start

**Comment by SvenSven2009** [comment]
![crash](https://cloud.githubusercontent.com/assets/2912582/5754452/18a22e1c-9caa-11e4-9a14-a561e7fc9152.png)

**Comment by SvenSven2009** [comment]
![crashc](https://cloud.githubusercontent.com/assets/2912582/5754475/5e62e37e-9caa-11e4-89c7-6690d3485380.png)

**Comment by marianneangelie** [comment]
Also encountered this but I fixed this by linking libMPCategoryHelpers.a in build phases

**Comment by malectro** [comment]
marking this as related to https://github.com/mixpanel/mixpanel-iphone/issues/225

**Comment by andrey-krukovskiy** [comment]
Hi, guys!
I had the same issue.
The reason for that well described here: https://developer.apple.com/library/ios/qa/qa1490/_index.html
So, for me solution was adding `-force_load path_to_the_libMPCategoryHelpers.a` to the `Other linker flags`

**Comment by daresayer** [comment]
Nothing above has worked for me, but what did work was commenting out:
```
controller.backgroundImage = [presentingViewController.view mp_snapshotImage];
```
in Mixpanel.m :/

**Comment by jakeapeters** [comment]
I just had the exact same problem. Adding `-ObjC` in Build Settings > Other Linker Flags for Debug and Release fixed it. Thanks to @malectro for documenting why here: #225

**Comment by samgreen** [comment]
This will be resolved in the next major release.

**Comment by samgreen** [comment]
This should be resolved now if you want to do a `pod install`.

**Comment by alpennec** [comment]
Hi guys,

I have the same problem on Xcode 6.4, building on iOS 8.
I'm using Carthage (github "mixpanel/mixpanel-iphone" "master")

2015-08-27 09:48:34.384    [4471:524526] -[UILayoutContainerView mp_snapshotImage]: unrecognized selector sent to instance 0x14c528300
2015-08-27 09:48:34.385    [4471:524526] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UILayoutContainerView mp_snapshotImage]: unrecognized selector sent to instance 0x14c528300'

Any idea why I'm having this crash?

Thanks
Axel
