### ISSUE TITLE
Crash related to MPObjectSelector.m

### ISSUE THREAD

**Issue by clkr** [mixpanel/mixpanel-iphone#231]
MPObjectSelector.m line 378
-[MPObjectFilter getChildrenOfObject:ofType:]

causes our app to crash. It happens after our table view controller's viewDidLoad is called.

**Comment by mad102190** [comment]
Not sure if this is related, but I'm actually having an issue here as well. I suspect that the call ````[((UIViewController *)obj).view isKindOfClass:class]```` is at fault here. Calling ````.view```` on a View Controller doesn't just access the view property, it actually tries to load the view in question. This is an issue since this is being called on a background thread. I've created a separate ticket to reference this issue specifically here: #263.

**Comment by crystaldonut** [comment]
Is there a workaround for this?

**Comment by clkr** [comment]
We stopped using Mixpanel because of the crashes. I'm unsubscribing from this issue.
