### ISSUE TITLE
archive / serial queue issues

### ISSUE THREAD

**Issue by BarakRL** [mixpanel/mixpanel-iphone#259]
1.
If you call trackEvent and immediately call archive, that event will not be archived as trackEvent will be done within the serial queue.
```
[self.mixPanel track:eventName properties:eventProperties];
[self.mixPanel archive];
```

2.
while the internal applicationWillTerminate does uses the serial queue:
```
- (void)applicationWillTerminate:(NSNotification *)notification
{
    MixpanelDebug(@"%@ application will terminate", self);
    dispatch_async(_serialQueue, ^{
       [self archive];
    });
}
```
on iOS 8.3 and iOS 7.0.3 (didn't check other versions), the archive isn't being performed on termination, I'm guessing that the app is terminated before the serial queue can perform the archive operation.

---

My (related) problem is that I try to track the event of the app terminating and was hoping to track and archive so mixpanel will send it on next unarchive however it cannot be done due to the above issue.

Since MixPanel is handling the application events itself, it would be nice if there was a delegate method that allowed last moment tracking and archiving.

**Comment by dgatwood** [comment]
The archive method really should dispatch itself asynchronously onto the serial queue.  As currently implemented, you risk a crash if you call archive yourself without explicitly doing so, because the arrays and dictionaries could be mutated on the serial queue while they're being archived on some other queue.

**Comment by dgatwood** [comment]
I think there's also a very subtle race condition with archiving in the following situation:

1.  Application calls one of the initializers from a non-main thread.
2.  The init method registers for notifications by calling setUpListeners.
3.  The user hits the home button before the next line of code.
4.  The applicationDidEnterBackground: method runs.
5.  That method starts archiving on the serial queue.
6.  The init method gets to the next line of code and unarchives itself while archiving is in progress.

That's probably not going to cause a crash, because unarchive replaces the object outright rather than mutating it, but it could cause the data being archived to not be what you expect.  And in the worst case, you might also try to unarchive a partially written archive, which could be problematic.

**Comment by dgatwood** [comment]
Moving the setUpListeners call below the unarchive call should fix that race condition, but the archive and unarchive methods should still probably both be serialized.

**Comment by arittr** [comment]
@dgatwood @BarakRL thanks so much for all the work and info here. we're going to take a look at working something like this into our next release - I agree that the potential last-minute failure with the archive method isn't particularly good behavior. appreciate the help - happy to take a look at a PRQ if you have any suggestions!

**Comment by yarneo** [comment]
Archive is now called on every track call, so this issue should no longer occur when an event isn't archived because of archive not being run on the internal serial queue. This means that there is no need to call archive right after a track call because it is already archived internally. Hope this resolves your issue!
