### ISSUE TITLE
Crash on -[Mixpanel flushQueue:endpoint:]

### ISSUE THREAD

**Issue by vj9** [mixpanel/mixpanel-iphone#276]
Fatal Exception: NSRangeException
*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds for empty array

0	CoreFoundation	__exceptionPreprocess
2	CoreFoundation	-[__NSArrayM removeObjectAtIndex:]
3     CoreFoundation	-[NSMutableArray removeObjectsInRange:inArray:range:]
4	Mixpanel.m line 775 -[Mixpanel flushQueue:endpoint:]
5 	Tracker.m line 132 -[Tracker flush]
6 	Tracker.m line 115 -[Tracker stop]
7 	PeopleMetricsTask.m line 68 -[PeopleMetricsTask perform]
8 	Task.m line 61 __19+[Task runClasses:]_block_invoke
9      Foundation	__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
10    Foundation	-[NSBlockOperation main]
11	Foundation	-[__NSOperationInternal _start:]
19	libsystem_pthread.dylib	start_wqthread

**Comment by arittr** [comment]
hey @vj9 - what version of the library is this? are you running the Mixpanel SDK on multiple threads? this looks to me like somehow an element in the queue to be flushed is being changed/removed during the flushQueue process.

**Comment by vj9** [comment]
Using mixpanel 2.6.2. Yeah this is being called in a separate thread.

**Comment by arittr** [comment]
hey @vj9 - our current release is v2.8.1 so you might want to try upgrading and see if that fixes the issue. that being said I think threading is the issue here - what operations are you doing from the separate thread? is there any possibility that this array is being touched from two threads at once (like tracking from one and flushing from the other)?

**Comment by bkvirendra** [comment]
I'm using the 2.8.1 and still getting the same crash at [Mixpanel flushQueue:endpoint:]
