### ISSUE TITLE
Clarification about Swizzling

### ISSUE THREAD

**Issue by schwa** [mixpanel/mixpanel-iphone#312]
Swizzling in general is _really_ bad and to be avoided. Especially when swizzling system provided classes. I'd like some clarification about when mixpanel swizzles OS classes.

When does Mixpanel swizzle? Can it be completely disabled? What functionality is lost by disabled swizzling?

**Comment by alex-hofsteede** [comment]
@schwa We use swizzling exclusively to run visual A/B tests and codeless event tracking on iOS. If you don't use either of these features, we will never swizzle your methods. 

In the cases where we do use it, we only swizzle methods like `didMoveToWindow` in order that we can know when an element that is being A/B tested appears on screen. This is so we can apply the A/B test changes to the element. We also make sure that the original function for the swizzled selector is called first, so that we do not introduce unwanted call latency into your app.

We have fairly complete tests in ABTestingTests.m that check a bunch of edge cases re: swizzling of different classes and selectors. If you are seeing an issue with swizzling when using A/B testing or codeless tracking, we'd be glad to look into it for you.

**Comment by alexgarbarev** [comment]
Hey. I faced with problem with swizzled code.The problem - it's slow. It runs every time something added as subview. In my application, I'm adding subview very frequently (while scrolling)

Here is stack trace from profiler:
![screenshot 2015-11-25 22 22 34](https://cloud.githubusercontent.com/assets/2268687/11402770/620deae2-93bb-11e5-8623-bd7128d780e9.png)

Can you advice me what do to here? How can I disable that?

**Comment by Axcic** [comment]
Hello! I'd like to turn off any swizzling, please say how can I do it?
