### ISSUE TITLE
Survey text stuck on single line, shrinks and truncates on iOS 9.1

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-iphone#385]
When sending a survey on iOS 9.1 and the text is longer than the size of a line, the text is being shrunken and eventually truncated due to the length of the message. The UI indicates it should be on multiple lines instead of shrunk -- the SDK should also perform this same multi-line display.

[Here](https://www.evernote.com/l/AfLLBXAvlj9P_rfbRZFOSrjtqEvRh46vUf0) is a zoomed screenshot and [here](https://www.evernote.com/l/AfKf0-nUUYdEt41TLOCaM2P3rt_cCKvtge8) is a non-zoomed screenshot -- it is broken on each.

**Comment by anderscarling** [comment]
Any updates on this? Would be nice to be able to use the survey feature..

**Comment by samgreen** [comment]
I'm not convinced there's much we can do for this. Sure we can extend it to two lines, but that doesn't really fix the problem it just extends the limit.

@anderscarling The survey feature works perfectly, but extremely long answers are being truncated. I think this is more of a product question than a bug.

**Comment by anderscarling** [comment]
I would argue that this is a bug, due to the fact that the online survey editor shows an entirely different behavior (which I would guess leads to quite a few users publishing broken surveys).

[This screenshot is of the online editor](https://cloud.githubusercontent.com/assets/49722/12568029/151b438c-c3c3-11e5-88ca-e40cc66a468d.png) and [this is a screenshot of the very same survey as rendered on the iPhone.](https://cloud.githubusercontent.com/assets/49722/12568038/24a73a72-c3c3-11e5-9401-7c9c597a532a.jpg)

I agree that extending to two line seams kinda pointless, but it's certainly not impossible (though it can be a bit tricky) to do dynamic label sizing based on label content (for "infinite" amount of lines, just as the online editor)
 If you don't feel that's a good fit for the library i would suggest updating the online editor to match the client library.

**Comment by samgreen** [comment]
Hey @anderscarling thanks for the reply with the screenshots! Giving this a second look, it should definitely be consistent with our web UI. We're taking a look at options now.

**Comment by yarneo** [comment]
Survey has been deprecated, thanks for opening this issue but we are no longer supporting the Surveys feature.
