### ISSUE TITLE
Random events tracking order

### ISSUE THREAD

**Issue by Toinouze** [mixpanel/mixpanel-iphone#398]
Hi,

The issue is really simple : 
    
    [[Mixpanel sharedInstance] track:@"Test"];
    [[Mixpanel sharedInstance] track:@"Test2"];

These two lines have a random result.
Sometimes, the "Test2" event will be displayed first, sometimes second.

Is there a way to prevent this ?

I assumed the SDK had an real queue which made sure everything was recorded in order. It appears it doesn't, and I'm a bit surprised. It could lead to serious bugs when creating aliases : 

    [[Mixpanel sharedInstance] createAlias:@"alias" forDistinctId:@"myId"];
    [[Mixpanel sharedInstance] identify:@"alias"];
    [[Mixpanel sharedInstance] track:@"Test"];

In this scenario, many "Test" events could be lost because they would be received before the "create alias" command.

One solution would be to send each event in a separate HTTP request and wait for each one to be successfull before sending the next one. Or at least warn that the SDK doesn't not support multiple events sent at the same second.

Thanks

**Comment by jaredmixpanel** [comment]
Hi @Toinouze,

It is only the display of those events in the Mixpanel.com UI which is random. The order in which events with timestamps less than 2 seconds apart are displayed cannot be guaranteed. Two events that close together will most likely have identical timestamps anyway. I would also note that the Mixpanel iOS library does in fact use a serial queue: https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L62

As for the alias issue, there can indeed be race conditions there. Even if the $create_alias event is received before the "Test" event there can be issues, because there is some additional time (usually a few hundred milliseconds) required to actually add the alias to our alias table.

Because of this, the preferred way of identifying immediately after creating an alias is to use the original distinct_id in the identify: call instead of the alias:

[[Mixpanel sharedInstance] createAlias:@"alias" forDistinctId:@"myId"];
[[Mixpanel sharedInstance] identify:@"myId"]; // use the original distinct_id
[[Mixpanel sharedInstance] track:@"Test"];

Then you only need to call [[Mixpanel sharedInstance] identify:@"alias"]; when users log in.

Thanks

**Comment by Toinouze** [comment]
Hi @jaredmixpanel, thanks for the quick response.

What about funnels though ? If i create a funnel with the first event sent less than 2 seconds before the next, is it guaranteed that my funnel will still work 100% of the time ?

Thanks !

**Comment by jaredmixpanel** [comment]
Hey @Toinouze 

Your boss is correct, our funnels have built-in 2-second window. See the section "What if two events are sent at the same time?" here: https://mixpanel.com/help/questions/articles/how-are-funnels-calculated

**Comment by Toinouze** [comment]
Fantastic. Thanks for your help @jaredmixpanel, closing the issue.
