### ISSUE TITLE
could mix javascript & native iphone library to talk to mixpanel?

### ISSUE THREAD

**Issue by pcompassion** [mixpanel/mixpanel-iphone#405]
I asked a question on stackoverflow, but thought this might be better place to ask.

http://stackoverflow.com/questions/34504690/mixpanel-for-hybrid-app

In short, can I use mixpanel-javascript for certain events and mixpanel-iphone for other events from a hybrid app?

**Comment by jaredmixpanel** [comment]
Hi @pcompassion, Jared from Mixpanel support here... while I've not yet heard of anyone using both libraries simultaneously, off the top of my head, I can't imagine any problems. It seems to me like it would work just fine but only testing will confirm. I would recommend taking a crack at it and if you run into any problems or have questions shoot me an email at support@mixpanel.com, either way I'd love to know how it turns out.

**Comment by pcompassion** [comment]
@jaredmixpanel Thanks for the answer. will do report if I test it out.

**Comment by nleovideo** [comment]
Hi @pcompassion, how the integration of both iOS and JS SDK is doing ? 
Are users tracking the same way even if the event is generated from a webview or a native screen of you hydrid app ? 
Finally what's happening with funnel if the user path crosses webviews and then native ? Can you track this user as a same person ? 

Thanks
