### ISSUE TITLE
defaultDistinctId should not be linked to the current device

### ISSUE THREAD

**Issue by Toinouze** [mixpanel/mixpanel-iphone#411]
Hi,

What should happen :

- app launch : distinct_id = MyUniqueId
- sign up : create alias (MyUniqueId, MyUserId)
- logout : distinct_id = MyNewUniqueId

What happens at the moment : 

- app launch : distinct_id = defaultDistinctId (IFA of the phone)
- sign up : create alias (MyUniqueId, MyUserId)
- logout : distinct_id = defaultDistinctId

which means any event sent after a logout will still be mapped to the user that just logged out.
Moreover, if a new user signs up after that, we'll have 2 aliases for the same distinct id which should never happen.

Suggestion : defaultDistinctId method should NOT be linked to the current device, but always a unique, new ID like [[NSUUID UUID] UUIDString]

Opinions ?

**Comment by jaredmixpanel** [comment]
@Toinouze I'm with you, I also think that the reset method should generate a new distinct_id. In fact, our Android SDK already does this in the reset() method. The issue here though, is that this would be a fairly fundamental change in the library's identify management flow, which is a bit concerning since there could very well be implementations out there depending on the current behavior in some way. I'd love to know @samgreen 's thoughts. 

That said, for now, it is simple enough to get your desired behavior with one extra line of code...

[[Mixpanel sharedInstance] reset];
[[Mixpanel sharedInstance] identify: [[NSUUID UUID] UUIDString]];

**Comment by Toinouze** [comment]
@jaredmixpanel yep, that's what we're doing at the moment. Hopefully it can be fixed in the SDK though.

Thanks

**Comment by samgreen** [comment]
You could also fix this by enabling `MIXPANEL_NO_IFA`. This wouldn't require any further code changes. I'm hesitant to make this change since we've already shipped with this behavior, and some clients may depend on the distinct id NOT changing between `reset` calls.

**Comment by cerupcat** [comment]
@samgreen I don't see how MIXPANEL_NO_IFA fixes this since it uses ` [[UIDevice currentDevice].identifierForVendor UUIDString];` if MIXPANEL_NO_IFA isn't defined and thus the UUID would still be the same between logouts. 

So, unless I'm missing something, the only way right now is to use:
`
[[Mixpanel sharedInstance] reset];
[[Mixpanel sharedInstance] identify: [[NSUUID UUID] UUIDString]];
`
Is that correct?

**Comment by yarneo** [comment]
@cerupcat you are correct, and you would still get the same unique identifier even without IFA. The only solution is to do the reset like @jaredmixpanel suggested.
