### ISSUE TITLE
A/B experiments persist even when turned off and backgrounded, until the app is re-launched

### ISSUE THREAD

**Issue by cassiegamm** [mixpanel/mixpanel-iphone#429]
**Outstanding issue:**
The app often requires TWO re-launches before reverting to default values (aka disabling an experiment). This makes it difficult to pull back on features/experiments we don’t want users to see anymore (bugs for example).

**Lack of Parity:**
I think from an engineering perspective parity is super important to keep things clear. Why should changes in variant distribution be applied immediately upon didBecomeActive but changing the experiment from ON to OFF not be applied until after the app is closed and re-launched? (sometime more than once). 

The ability to turn off an experiment quickly is important in the case of major unpredicted bugs, or a business externality.  App relaunch is much slower than app active.

Ideally, engineers should have the option of customizing the behavior that applies (or removes!) experiments during didBecomeActive.

**Comment by ryanseams** [comment]
i wanted to shed some additional light on this issue with the results from some testing.

i found that when a test is either: 1) turned off OR 2) the variant allocation is changed, you must make a call to ```[mixpanel checkForDecideResponseWithCompletion:completion useCache:NO];``` in order to force the SDK to get an update from Mixpanel. in this update, you will receive a new response from the /decide server based on the changes you make in the web UI.

at the point of receiving and applying the experiment (the cache clearing and experiment application all happens by default in ```joinExperimentsWithCallback:```), two things happen: 1) any UI changes are discarded from the prior experiment AND 2) tweaks remain applied from the prior experiment, not the new one.

i would expect, given the behavior says useCache:NO, that we simply discard the old A/B test and apply whatever is received (a new variant, or the original app experience). i believe the issue here is tweak values continue to persist, which appears to be some sort of issue with how the SDK manages the variants [here](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L1324-L1340).

let me know if i can assist further or provide any additional context here as needed.

**Comment by samgreen** [comment]
Resolved with #442
