### ISSUE TITLE
Can not build and run  while run app in iOS 7 device.

### ISSUE THREAD

**Issue by PayalUmraliya** [mixpanel/mixpanel-iphone#482]
My application is working correctly in ios 8.0 and above but when i try to run my app in xcode 5.1.1 as my application is compatible with ios 7.0 and above but it shows me lots of error in mixpanel.h file

**Comment by samgreen** [comment]
Hi @SaraMichel, sorry you're having trouble with the SDK. Can you tell me what integration method you are using? I have run in to this error before when attempting to use a dynamic framework on iOS 7 since they are not supported. 

It would also be really helpful to see a list of the errors you are receiving.

**Comment by PayalUmraliya** [comment]
What is the minimum ios version required in mixpanel api ?

I integrated mixpanel using drag and drop method without using pods.
libcuicore.tbd file is required so i added that file also.

so after that my application works fine in ios 8 and above.
I tried to run my app in xcode 6.1 iphone 4s (ios 7.1) simulator but it show me compile time error
here is the screen shot.

![screen shot 2016-05-09 at 11 51 57 am](https://cloud.githubusercontent.com/assets/14552882/15105280/0123cc10-15de-11e6-987e-eb0cdc05d0fe.png)

**Comment by Coeur** [comment]
@PayalUmraliya, please note that Itunes Connect has recently dropped support for Xcode 5. So if you plan to publish your app on Itunes Connect, it will require Xcode 6.0 at least.

**Comment by Coeur** [comment]
@PayalUmraliya, from your screenshot: `NS_ASSUME_NONNULL_BEGIN` is only defined with Xcode 7. So commit https://github.com/mixpanel/mixpanel-iphone/commit/6d270c9888dabba884291aa462d2339e24140825 from December 2015 has broken support for older versions of Xcode.

@samgreen, would you like me to help providing a compatibility solution for Xcode 6?

**Comment by PayalUmraliya** [comment]
Ok but what about iOS 7 ?

**Comment by Coeur** [comment]
iOS7 is well supported, it's Xcode 6 support that got broken.

**Comment by Coeur** [comment]
@PayalUmraliya, you may attempt to add those lines for Xcode 6 compatibility:

    #define NS_ASSUME_NONNULL_BEGIN
    #define NS_ASSUME_NONNULL_END
    #define nullable
    #define nonnull

But I can't guaranty it will be enough (as I haven't tried it yet).

**Comment by Coeur** [comment]
@samgreen, any feedback on this?
* Xcode 6 support was broken since December 2015
* Xcode 8 beta will be released in 5 days (WWDC)

We can either re-introduce support for Xcode 6 (but in that case we can't use lightweight typing syntax from Xcode 7) or Mixpanel can officially drop support for it (and in that case we can remove a couple of lines in MPFoundation.h, but I wouldn't delete the file as we will need it once Xcode 8 is released).

**Comment by samgreen** [comment]
@Coeur We're discussing internally. We will get back to you this week.

**Comment by samgreen** [comment]
Looks like we have made a decision here. v3.0.0+ will only support iOS 8 and Xcode 7 and above.
