### ISSUE TITLE
Can't build with latest version 3.0.0

### ISSUE THREAD

**Issue by namanhams** [mixpanel/mixpanel-iphone#536]
**Integration Method:** Cocoapods 
**Xcode Version:** 7.3.1
**Library Version:** 3.0.0
**Platform:** iOS 
**Device:** Simulator 

**Description:** When build with version 3.0.0, the compiler gives error "definition of 'Mixpanel' must be imported from module 'Mixpanel.Mixpanel' before it is required My project is Objective-C
**Expected Behavior:** When i revert back to 2.9.9, everything is fine.

**Comment by samgreen** [comment]
Hi @namanhams Can you please post the contents of your bridging header?

**Comment by samgreen** [comment]
Can you confirm that you have `#import <Mixpanel/Mixpanel.h>` in that same file that you're receiving the error? Although the error looks like it might be from the module system. Are you instead using `@import Mixpanel;`?

Otherwise I think it must be an issue with your project configuration. I created a new clean project in Objective-C and integrated v3.0.0 of the CocoaPod. I'm able to build and send events. I attached the sample project in hopes that it might help you figure out what setting is wrong in your project.

[MixpanelCocoaPod300.zip](https://github.com/mixpanel/mixpanel-iphone/files/337667/MixpanelCocoaPod300.zip)

**Comment by namanhams** [comment]
I follow the instruction and do "#import "Mixpanel.h" instead. But this works fine for 2.9.9. It just doesn't work for 3.0.0. I'll clean and try again and let you know

**Comment by samgreen** [comment]
Did this resolve your issue?

**Comment by hamdullahshah** [comment]
I'm facing the same issue, i just updated my pod and now it's not working with 3.0.0

**Comment by samgreen** [comment]
@hamdullahshah Can you please open a new issue and fill out the template so we can keep each issue focused?

**Comment by natanrolnik** [comment]
@samgreen I was having the same issue, because I was importing `#import "Mixpanel.h`. Changing to `@import Mixpanel;` fixed it.

**Comment by samgreen** [comment]
Marking issue as resolved.
