### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by mltk96** [mixpanel/mixpanel-iphone#572]
**Integration Method:** CocoaPods version 1.1.0.rc.2
**Xcode Version:** 8
**Platform:** iOS + share extension 

**Description:** 
i'm using Mixpanel for both the main app and my share extension app.
and had the "pod 'Mixpanel'" for the main app, and the "pod 'Mixpanel/AppExtension'" for the share extension.
but after moving to Xcode 8, i had to start using the latest beta version of Cocoapods which is 1.1.0.rc.2 and since then the cocoa pods installation stopped working with the following error:
[!] The 'Pods-MainAPP' target has frameworks with conflicting names: mixpanel.

any advice?

**Comment by mseijas** [comment]
Having the same issue here

**Comment by yarneo** [comment]
Thanks for the update guys. We are working on fixing this and will provide a fix shortly

**Comment by mseijas** [comment]
@yarneo Thanks! Any idea what might be causing this? I need to submit an app for review and this is the only thing holding me back. If you could provide any insight that would be amazing. Thx

**Comment by yarneo** [comment]
hey @mseijas, the reason is that when using the Mixpanel in both the app itself and the extension, there seems to be a conflict because it creates 2 frameworks of the same name in one app.
It seems to be an open issue in Cocoapods: https://github.com/CocoaPods/CocoaPods/issues/5643
A workaround would be to integrate Mixpanel manually or we would need to send out another pod with a different name just for extensions. 
We will look into this more tomorrow

**Comment by mseijas** [comment]
@yarneo great - thanks for the fast response! i actually just realized how i had two frameworks with the same name, was thinking of trying to manually integrate it :fingers-crossed:

**Comment by mltk96** [comment]
any updates?

**Comment by yarneo** [comment]
Ma kore Michael ze Yarden!

There aren't any updates yet, it seems to be a cocoapods issue: https://github.com/CocoaPods/CocoaPods/issues/5643 . I will still try to see what workarounds are possible, but as for now I recommend integrating the Mixpanel SDK manually for the extension.

**Comment by mltk96** [comment]
tnx Yarden! :)

**Comment by yarneo** [comment]
Hey! Thanks :) I will try to see today and Monday if we can find a way around this! Will keep you updated

**Comment by yarneo** [comment]
Ok guys, I have good news, I have found a workaround for this issue.

**The problem:**
The latest pre-release version of Cocoapods (1.1.0.rc.2) fixes an issue with the extension pods that aren't embedded. However, it gives the conflicting names error.
The current release for Cocoapods (1.0.1) doesn't give you the conflict error but doesn't embed the extension pods.

**The solution:**
Have your Podfile look like so:
pod 'Mixpanel/Mixpanel' <- in the app target
pod 'Mixpanel/AppExtension' <- in your extension target

and issue a 'pod install' with version 1.0.1.
If you have multiple cocoapod versions installed you can do: 'pod _1.0.1_ install'

You shouldn't get a conflicting names error at this point.

Now you need to go to your project, to the Mixpanel extension target, and add the run script that is missing for embedding the pods.

Name the run script: [CP] Embed Pods Frameworks and place it before the [CP] Copy Pod Resources script in your Build Phases. 
In this run script put the exact same command as what you see in [CP] Copy Pod Resources script, but change the ending of "..-resources.sh" to "..-frameworks.sh"

Hopefully this will work well for you guys. Let me know if this resolves the issue!

**Comment by mltk96** [comment]
unfortunately this will not work for me, as i need Cocoapods version 1.1.0 to support Xcode 8 and the latest Alamofire SDK

**Comment by yarneo** [comment]
I was using Xcode8 for this process, what issue do you see with using 1.0.1?

**Comment by yarneo** [comment]
I see that Alamofire requires 1.1.0 in their notes. Well there's not much I can do with this I'm afraid as this is a cocoapods issue. That's the best workaround I can give to bypass their bugs

**Comment by mltk96** [comment]
fair enough.
tnx for investigating it though!

**Comment by yarneo** [comment]
Hey @mltk96 , 
to try and help you get Mixpanel integrated properly I created a forked version of Cocoapods that will allow you to install Mixpanel in the extension & app, and be able to use Alamofire because it is a fork of version 1.1.0rc2.

What you need to do is write this in your command line:
gem install specific_install    
gem specific_install -l https://github.com/yarneo/cocoapods.git

^ The installation will take about 5-10 minutes because it is taking a specific branch, but this will resolve the issues you have. I am closing this issue for now because it is a Cocoapods bug and we have a workaround solution for this specific case. Feel free to reach out if you need anymore help.

**Comment by mltk96** [comment]
@yarneo instead of having this workaround, is there a chance you can make the main Mixpanel SDK to support extensions? by handling it yourself and differentiating whether it runs from the regular app or an extension app?

**Comment by nickvelloff** [comment]
Has not worked since CocoaPods 1.0.1 ... you can pod _1.0.1_ install but we can't stick there forever. Cocopods does not see this as their issue.
FWIW I install with `1.0.1` and use the latest Alamofire `Using Alamofire (4.2.0)`
