### ISSUE TITLE
Documentation For distinctId outdated?

### ISSUE THREAD

**Issue by mamaral** [mixpanel/mixpanel-iphone#586]
The header documentation for the `distinctId` property says that you default to a hash of the device's MAC address, although the actual implementation looks like it tries to get the device's identifier for advertising, if it can't get that it tries to get the `identifierForVendor`, and if it can't get that falls back to generating a normal UUID string.

Am I missing something, or is the header just out of date? I can submit a PR if you'd like - let me know!

**Comment by yarneo** [comment]
Hey @mamaral, you are so very right! It seems that when the newer implementation for the default distinctID was pushed, the documentation remained the same and is indeed outdated.

As you said, we first check if the project has the AdSupport library and that the user did not limit tracking. If that is the case we fetch the advertising Identifier, otherwise fallback to the vendor identifier, and finally to a random UUID string. 

If you could submit a PR that would be fantastic! Cheers!

**Comment by yarneo** [comment]
Thank you @mamaral !!! Closing the issue
