### ISSUE TITLE
Crash on connectToABTestDesigner

### ISSUE THREAD

**Issue by aurimastg** [mixpanel/mixpanel-iphone#597]
The following line crashes when doing A/B testing:
`MPDesignerTrackMessage *message = [MPDesignerTrackMessage messageWithPayload:@{@"event_name": event_name}];`

`event_name` is nil and exception is thrown because it tries to construct dictionary with nil value.

Using the latest released SDK version (3.0.5) with Xcode 8.0.

**Comment by pchien** [comment]
Hi @aurimastg. Do you have any track calls with `nil` for the event string? From what I can tell, that line is called in a swizzled version of the `track:properties:` method where `event_name` is whatever you passed in for `event`. If that's the case, changing it so you have a named event instead of `nil` should fix this issue. If that doesn't work, can you provide a stack trace or crash log? Hope this helps!

**Comment by aurimastg** [comment]
I had track calls with `nil`. Thanks for help @pchien, problem solved, closing this issue.
