### ISSUE TITLE
iOS 10 deprecated API warnings

### ISSUE THREAD

**Issue by brightsider** [mixpanel/mixpanel-iphone#613]
<img width="1180" alt="mixpanel" src="https://cloud.githubusercontent.com/assets/4996231/20244530/e05f8dda-a98e-11e6-862a-8d6b61baf1a6.png">

**Comment by pchien** [comment]
Interesting. Looks like `asl` still works in iOS 10 but it will show this compiler warning. It's been replaced by `os_log` as per https://developer.apple.com/reference/os/1891852-logging. However, when I tried importing `<log.h>` it gave me a file not found error. Not sure if this is an issue with the project or something with Xcode/Apple but I'll leave it for now since it's not actively breaking. If you have further insight on how to use Apple's new logging I'd love to hear it.

**Comment by yarneo** [comment]
`#import <os/log.h>` should work. We will probably reimplement the logging system in future, but for now we are going to leave it as is until we can figure out the best way to approach this with a logging system that supports iOS8 and upwards whilst removing any deprecation warnings. Closing this issue for now.
