### ISSUE TITLE
Crashing on mixpanel.collectproperties method 

### ISSUE THREAD

**Issue by jamespotts** [mixpanel/mixpanel-iphone#614]
**Integration Method:** CocoaPods / Carthage / Manual
**Xcode Version:** 
**Library Version:  
**Platform:** iOS
**Device:** iPad
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** On jailbroken devices, crashing is reported when using the mixpanel.collectproperties method.
**Expected Behavior:** Uncertain because of the device's jailbroken status

**Comment by yarneo** [comment]
Hey @jamespotts thanks for reaching out. We currently don't support jailbroken devices due to the fact that they allow users to alter the device's default behavior and hence cause unpredictable results. Specifically if it crashes in the collectProperties method it means that one of the phone's internal properties has been manipulated, i.e. device model, carrier, ifa, app information, and more.
