### ISSUE TITLE
Mixpanel interfering with UIPanGestureRecognizer

### ISSUE THREAD

**Issue by timothycosta** [mixpanel/mixpanel-iphone#623]
**Integration Method:** CocoaPods
**Xcode Version:** 8.1
**Library Version:** 3.0.7
**Platform:** iOS
**Device:** Any
**Language:** Objective-C

[ ] A/B Testing Manually Disabled? (DISABLE_MIXPANEL_AB_DESIGNER)

**Description:** 
Initializing mixpanel stops `UIPanGestureRecognizer` from updating to `UIGestureRecognizerStateChanged`.  I still receive `UIGestureRecognizerStateBegan` and `UIGestureRecognizerStateEnded`

My view hierarchy is as follows:
```
- Full Screen Presented View Controller / View
-- container view - Holds UIPanGestureRecognizer
--- Child View Controller / View
```

Commenting out `[Mixpanel sharedInstanceWithToken:@"..."]` fixes the issue.

**Expected Behavior:** 
`UIGestureRecognizerStateChanged` should fire as expected

**Comment by pchien** [comment]
Hi @timothycosta. I tried to reproduce this but I couldn't get it to happen - adding a pan gesture to our demo app seems to get Begin, Changed, and Ended. We have a pan gesture recognizer in the notification view so was that showing when you had the issue? Otherwise, I think the only long-lived gesture recognizer we have is the connect one, so maybe try setting `enableVisualABTestAndCodeless` to `NO` and seeing if that helps. Let me know if any of that works!

**Comment by timothycosta** [comment]
Hi @pchien.  I wasn't able to duplicate this in a test project either.  Our view/view controller hierarchy is fairly complex where this is occurring.  But using `enableVisualABTestAndCodeless = NO` does seem to fix the issue.  Does this mean we can't use AB tests at all, or just the visual AB testing tool?  Is there anything I should be aware of when using that setting?

**Comment by pchien** [comment]
As far as I know it prevents you from using the A/B testing tool and the codeless events tool on the website. Your current A/B tests will still run, and if you set ones up in a build with `enableVisualABTestAndCodeless = YES` you can get those in live. It will make it less convenient for you to set up new A/B tests since you won't be able to do it on your live build but if it's causing more issues for you right now it should be fine to turn off. Thanks for the info though, should be informative for debugging this issue.

**Comment by pchien** [comment]
The only things I can think of right now are if you have [gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:](https://developer.apple.com/reference/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer?language=objc) or [gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:](https://developer.apple.com/reference/uikit/uigesturerecognizerdelegate/1624222-gesturerecognizer?language=objc) implemented and defaulting to failing if the other gesture recognizer (in this case the A/B testing one from Mixpanel) is unrecognized. Is that the case?

**Comment by timothycosta** [comment]
Forgot to add, I did test a notification when I set mixpanel up last week, but I don't believe the notification itself was the problem.  It was created for only one user, and I deleted it after I confirmed that it had worked.  Right now there should not be any notifications being sent to the app.

**Comment by timothycosta** [comment]
@pchien It looks like I am returning `YES` on `shouldRequireFailureOfGestureRecognizer`.  I can't just return `NO` however, as that makes the gesture trigger too easily (subview contains a tableview).

Right now we're not using A/B tests so I guess turning that off is fine for the moment.  Is there a more general solution here if we want to use that in the future?  I guess I would have to let all my gesture recognizer delegates be aware of mixpanel's gesture recognizer?  That seems like it could be a bit error prone though.

**Comment by pchien** [comment]
Interesting. It's possible that you could set a delegate for our gesture recognizer and then with `gestureRecognizer:shouldRequireFailureOfGestureRecognizer:` return `NO` if the first `gestureRecognizer` is Mixpanel's. Currently our gesture recognizer is private (https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MixpanelPrivate.h#L60) though I think you should be able to expose it with a category. Beware that the gesture recognizer initializes on a `dispatch_async` (https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L996-L997) so you can't set the delegate on the same runloop as you initialize Mixpanel.

Not sure that this is the best solution but it should work and will also allow you to use A/B testing functionality normally.
