### ISSUE TITLE
How to choose one of them {mp_varA，mp_varB,mp_varC，mp_varD,mp_varE}

### ISSUE THREAD

**Issue by ganvinalix** [mixpanel/mixpanel-iphone#646]
I find event path  ( "/ViewController/UIView/UIButton[(mp_fingerprintVersion >= 1 AND mp_varE == \"bf542ca1ca91ed5693798fe58a8b0641b0e15a3c\")]";") ,will use one of them {mp_varA，mp_varB,mp_varC，mp_varD,mp_varE}.I want to know that this strategy is how to implement。why some time is  mp_varE ,some time is mp_varB?What is the priority order？ thx!

**Comment by yarneo** [comment]
Hey @ganvinalix ! We use these vars as identifiers for views in A/B testing so we know which views we want to target. mp_varA is used to get the viewID (which is an identifier views get when they are set up in storyboards/xibs. mp_varB identifies viewControllers by appending their instance vars together to a string. mp_varC gives you a UIImage unique identifier, mp_varD is for UIControls, and mp_varE is for UILabels or other elements that have text in them. That's why sometimes certain elements use different mp_vars, because these each element is identified in a different way based on its type. There is no priority between them, sometimes it is useful to have multiple identifiers to make sure it is the right one, hence you see mp_fingerprintVersion and mp_varE for the same one.

**Comment by ganvinalix** [comment]
@yarneo thank you!
