### ISSUE TITLE
Swift vs Objective C library

### ISSUE THREAD

**Issue by f2prateek** [mixpanel/mixpanel-iphone#665]
Hi,

I noticed that the docs recommend that for users using swift, it's better to use the swift library https://github.com/mixpanel/mixpanel-swift.

It doesn't say why this is recommended though. Is it just because the swift version has a nicer API for interacting with swift and is easier to setup, or is there some stability or feature disparity between the two?

**Comment by yarneo** [comment]
Hey @f2prateek thanks for writing in. There is a full feature parity between the Objective-C and Swift SDKs. 

As for what you should use, you can definitely use both, but we encourage our Swift users to use the Swift repo not only for the nicer API, but also for various other reasons. Here are a bunch:
1. No need to add Mixpanel to any sort of bridging header, less boilerplate code.
2. The Objective-C SDK would get a generated Swift API that you would interact with, so you are adding another layer to the interaction with the API.
3. You will not make full use of the Swift capabilities. As an example, in our Swift SDK we have the properties that are sent built from a type called MixpanelType. Your Swift project won't compile due to its strongly typed nature if you send a property that doesn't conform to MixpanelType. On the other hand, in the Objective-C repo you will get an NSException at runtime.
