### ISSUE TITLE
Temporal Order of Events

### ISSUE THREAD

**Issue by mamaral** [mixpanel/mixpanel-iphone#676]
**Integration Method:** Carthage
**Xcode Version:** 8.3.1
**Library Version:** 3.0.4
**Platform:** iOS
**Language:** Objective-C
**Description:** Tracking events that happen very close to one another, potentially within .0x seconds, results in undefined/out-of-order events. Two events, let's call them A and B, might happen so close together, like at time xxx.22 and xxx.27 that in the live view they show up as A, B and in the profile view they show up as B, A.
**Expected Behavior:** The true order of events is maintained, even within the same second. This is largely for use in funnels where the order is extremely important.

I'm *assuming* the order of events as shown in the live view or profile view is based on the time value of the events. If two events happen during the same *second* in time, that appears to result in ambiguous ordering of those events in the UI. I believe this is due to the fact that the timestamp is rounded (Mixpanel.m line 374):

```
NSTimeInterval epochInterval = [[NSDate date] timeIntervalSince1970];
NSNumber *epochSeconds = @(round(epochInterval));
dispatch_async(self.serialQueue, ^{
   NSNumber *eventStartTime = self.timedEvents[event];
   NSMutableDictionary *p = [NSMutableDictionary dictionaryWithDictionary:self.automaticProperties];
   p[@"token"] = self.apiToken;
   p[@"time"] = epochSeconds;
```

Is rounding a requirement for the API or database? Any info would be greatly appreciated!

**Comment by cassiegamm** [comment]
Hi @mamaral,

Seeing events out of order in Live view or in Activity Feeds, or having events with identical timestamps, will generally not affect other parts of your reporting. Mixpanel employs a two-second grace window on Funnel and Retention reports so that if you do have events that launch simultaneously, Funnel reports will not break.

[Mixpanel Funnels include a built-in 2 second window](https://mixpanel.com/help/questions/articles/how-are-funnels-calculated). This means any consecutive steps that have timestamps within two seconds of one another are interchangeable. This window allows for inconsistencies that arise with cross-platform tracking, batch event sending, mobile time tracking, or variations in connection speed.

As an example: In a funnel with step A -> B, if a user completes event B first and then performs event A within two seconds, Mixpanel will count this as a conversion from A -> B or B -> A.

**Comment by mamaral** [comment]
For additional context, this is easily reproduced by doing something like the following:

```
for (NSUInteger i = 0; i < 50; i++) {
            [[Mixpanel sharedInstance] track:[NSString stringWithFormat:@"test %@", @(i)]];
}
```

As you can see, the order is undefined:

<img width="161" alt="screen shot 2017-06-01 at 2 49 21 pm" src="https://cloud.githubusercontent.com/assets/6086409/26695645/9676a9ae-46d9-11e7-88a7-6ab140a045bf.png">

**Comment by mamaral** [comment]
@cassiegamm Awesome! That is really cool, thank you very much for the insight!! 👍

**Comment by adadgio** [comment]
I understand the issue is closed and funnels are not impacted but it seems its quite a big issue for view/live view, or probably other parts of Mixpanel features... whats the actual reason for events not to show up in correct order (its the same for Android and Javascript SDK by the way).
