### ISSUE TITLE
Baseline of event fired in applicationDidBecomeActive: has jumped up by ~3%

### ISSUE THREAD

**Issue by simX** [mixpanel/mixpanel-iphone#684]
**Integration Method:** Carthage
**Xcode Version:** 8.3.x
**Library Version:** 3.1.2
**Platform:** iOS
**Language:** Using the Objective-C Mixpanel library, but mixed use of Swift/Obj-C in our app
**Description:** 

We're tracking a Mixpanel event upon launch of our application, and we've noticed that after upgrading the Mixpanel library from 3.0.7 to 3.1.2, the baseline for our event has increased by quite a lot.  Here's an abbreviated version of our code from our app delegate:

```
    func applicationDidBecomeActive(_ application: UIApplication) {
            if AppSession.shared().isSessionActive {
                EventTracker.shared().appActivated()
            }
    }
```

We've looked at the release notes of the Mixpanel library, but it doesn't seem like anything would cause an increase in our baseline.  Just wanted to see if anybody has seen anything remotely similar.  The "April 17" data point here represents the week of April 17-23 which used library version 3.0.7, and the next data point is April 24-30 which uses library version 3.1.2.  You can see the significant uptick for the next 4 weeks.  It represents ~3% uptick over the baseline previously, which doesn't seem like much, but we're talking about around 2.5M events, which makes the uptick (I think) statistically significant.

![schermata 2017-06-13 alle 17 17 52](https://user-images.githubusercontent.com/49855/27110178-4504d6ae-505c-11e7-9b0a-cda0ff0fd944.png)

**Expected Behavior:** 
No significant deviation in expected number of events tracked in the applicationDidBecomeActive: method.

**Comment by cassiegamm** [comment]
Hi @simX,

Could you share your mixpanel project id with us so that we can take a closer look? It's the 5-7 digit number that appears in your reporting URL after [https://mixpanel.com/report/](https://mixpanel.com/report/). 

Thanks a bunch!

**Comment by simX** [comment]
311221

Thanks for looking into this!

**Comment by pchien** [comment]
Hi @simX. I took a look at your project and looked at the event you're referencing. I noticed that your unique users are trending up over time (congrats!), which actually explains some of the fluctuations in the total events sent. I did the rest of the analysis looking at average for that event (totals / uniques for that week). It looks like you had spikes around valentine's day and mother's day which make sense for your business. Otherwise, average was relatively flat before mother's day, and has gone up by ~10% after that compared to before. However, looking over a year it's not higher than it's ever been historically, i.e. around a year ago average was also around the same. Maybe there's some product based explanation for why your average app opens has gone up? I don't think we have changed anything that would cause the effect you're seeing. I'm happy to help with any other questions you might have.
