### ISSUE TITLE
Any way to disable Automatic Crash Reporting

### ISSUE THREAD

**Issue by saurabha5** [mixpanel/mixpanel-iphone#704]
**Integration Method:** CocoaPods
**Xcode Version:** 8.3.3
**Library Version:** 3.1.8
**Platform:** iOS 
**Language:** Objective-C
**Description:** Disable Automatic Crash Reporting 
**Expected Behavior:** Mixpanel is having conflict with Apteligent/Crittercism, so is there anyway to disable Crash Reporting from Mixpanel ?

**Comment by pchien** [comment]
@saurabha5 what's the conflict you're getting? We don't have any flags for disabling crash reporting right now. Could you also try switching the order of initialization between Mixpanel and Apteligent/Crittercism? This shouldn't cause an issue, but Mixpanel's exception handler will call the previously set one when it happens, and potentially Apteligent/Crittercism doesn't do that. At worst I think all that could happen is Mixpanel's isn't called and the other one is though. Let me know what you find out!

**Comment by saurabha5** [comment]
Basically, I don't see crash reported to Apteligent/Crittercism. The troubleshooting steps show that there is a change in NSGetUncaughtExceptionHandler.  Used below to print handler after both Mixpanel and Apteligent is initialized and at various point in the application and this shows the value is changed.

NSLog(@"Handler : %p", NSGetUncaughtExceptionHandler());

As you suggested and I tried before also to switch the order after this Apteligent started reporting the Crashes. Mixpanel first and then Apteligent. If at all there could be a way to completely tell Mixpanel not to register for Exception then it would have been a cleaner solution.

**Comment by pchien** [comment]
It's strange that it was an issue. From https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MixpanelExceptionHandler.m#L73 and https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MixpanelExceptionHandler.m#L174 it looks like we should be calling the previously set exception handler within our exception handler. So it's expected that the value of the handler is changed, but we shouldn't be cutting Apteligent out of the loop. I'll try to take a look when I get time, but it's good that this helped fix your problem.

**Comment by banaslee** [comment]
We had the same issue, it was stealing most of our crashes from HockeyApp. 
Since HockeyApp was our only crash tracking tool and Mixpanel was just used as an app events tracker, we were setting up HockeyApp first.

I understand that in order to take advantage of this automatic crash tracking I'd have to set it up before but that's outside the scope of our usage of Mixpanel as a tool and we won't upgrade until we can turn automatic crash tracking off.

On another perspective, IMO it changes the API therefore it should have been numbered as 3.2 instead.

**Comment by JAStanton** [comment]
I'll piggy back off of this. Sentry uses KSCrash under the hood for error/exception handling. I had to fork Mixpanel and comment out the setup handler method for registering all the exception handles and I was hoping there was going to be a way to disable registering of the exceptions handler.

- Jonathan

**Comment by pchien** [comment]
This should be fixed in the latest release via https://github.com/mixpanel/mixpanel-iphone/pull/718.
If that doesn't work for you, there's also an option to not setup our signal and exception handlers when initializing Mixpanel.
```objective-c
- (instancetype)initWithToken:(NSString *)apiToken
                launchOptions:(nullable NSDictionary *)launchOptions
                flushInterval:(NSUInteger)flushInterval
                 trackCrashes:(BOOL)trackCrashes
```
Initializing this way will still allow you to access later on with `sharedInstance` or `sharedInstanceWithToken:`.
