### ISSUE TITLE
Mixpanel does not create account after alias and identify called

### ISSUE THREAD

**Issue by tomkowz** [mixpanel/mixpanel-iphone#729]
**Integration Method:** CocoaPods
**Xcode Version:** 9.0
**Library Version:** 3.2.0
**Platform:** iOS
**Language:** Swift project, still using Objective-C library
**Description:** 

Calling following code mixed with `track:properties:` method ends up with properly uploaded events in Live view of Mixpanel, but there is no user created.
```swift
// track some events
alias(with: user)
identify(with: user)
// track some events
```

`user.id` is UUID basically.

```swift
    // MixpanelAnalytics.swift

    func alias(with user: MixpanelAnalyticsUser) {
        mixpanel.createAlias(user.id, forDistinctID: mixpanel.distinctId)
        DDLogDebug("Mixpanel: Did create alias")
    }

    func identify(user: MixpanelAnalyticsUser) {
        mixpanel.identify(user.id)

        mixpanel.people.set([
            "$email": user.email,
            "$first_name": user.firstName,
            "$last_name": user.lastName,
            "User ID": user.id,
            ])

        
        DDLogDebug("Mixpanel: Did identify")
    }
```

Not calling `mixpanel.createAlias...` with user's id ends up with user created on mixpanel but only events recorded after calling `identify` are linked to the user.

After calling `createAlias` and then `identify` with user's id as an alias ends up with no user on mixpanel.

Tested on new project on mixpanel.

**Expected Behavior:** 
I would like to have this scenario covered:
1. User goes through onboarding and records some mixpanel events anonymously
2. User did sign up so I call `createAlias` (with user's id), `identify` (with user's id) and `people.set` with properties like email and first/last name
3. User gets created on mixpanel and visible in Mixpanel's "Explore" section
4. Anonymous events performed before sign up are linked now to this new account on mixpanel.
5. New events are linked to newly created user.

Thank you in advance!

**Comment by pchien** [comment]
Hi @tomkowz I know this is confusing, but right now you have to call `createAlias` with the user's id and `identify` with the mixpanel distinctid (the user's original id) the first time. After the first time, calling `identify ` with the user's id works. We're looking to change this soon so it's more intuitive. There's an example [here](https://mixpanel.com/help/reference/ios#user-identity). Hope this helps!

**Comment by tomkowz** [comment]
@pchien thank you for your help. It started to work!

**Comment by cmsepul** [comment]
Hi @pchien . I ran into the same issue and found that this logic changed here: https://github.com/mixpanel/mixpanel-iphone/pull/708.

I see how given that change now the first `identify` call needs to be with the `distinctId` instead of the `alias`, but that doesn't seem to be clean:  it does conflict with the purpose of having an alias and it makes the implementation confusing with this special case for where using the alias has unexpected consequences. Specifically: why is the processing of the `unidentifiedQueue` now depending on not using the alias in the first identify?


The change seems to be a mistake to me, but I must be missing something, could you provide more context on what drove that change?
Thanks!

**Comment by pchien** [comment]
Hi @cmsepul. `alias` and `identify` has been confusing for a while, but I'll start here by saying in the latest release of the library we've made a change so that you no longer have to call `identify` after `alias` https://github.com/mixpanel/mixpanel-iphone/pull/730.

We made `identify` using the `alias` a no-op because otherwise there could be a race condition in our backend that could cause two people profiles to be created for the same user, one with the original distinct id and one with the alias as the distinct id. Since we can't really identify as the alias, we also don't set the people distinct id to the alias as we always want the people distinct id and the distinct id to be the same. That's why we don't process the unidentified queue there.

The latest version of the library should sort out all the confusion though, as it implicitly identifies when you call alias, and then on future sessions it's safe to call identify with your alias (the race condition will be gone by then). Hopefully that solves your issue!

**Comment by cmsepul** [comment]
Thanks a lot @pchien for the prompt and clear response!
I'm giving the latest version a try.

**Comment by MaroofKhan** [comment]
Hey @cmsepul! Did using the new version solve your problem?

**Comment by cmsepul** [comment]
hey @MaroofKhan , thanks for checking in! 
It did fix the issue, although we're still seeing some our users getting events tracked (can find them querying a super property using the jql console) but don't see their `People` profile getting created, and it's only for some portion (~7%) of users, not all of them. Is there anything else eventually affecting the `people` calls that you aware of?
Thanks!
