### ISSUE TITLE
Support currency in trackCharge

### ISSUE THREAD

**Issue by virl** [mixpanel/mixpanel-iphone#74]
[[Mixpanel sharedInstance].people trackCharge:] is totally useless under iOS, because it doesn't allow to send _currency_ of charge and developer have to convert all charges to single currency (which he will not do).

**Comment by ericcheungidea** [comment]
+1

The mix panel revenue feature is comprehensive but it is useless if no multi-currency conversion/ handling.

**Comment by Suhail** [comment]
Hey, we're planning on handling currency conversion in a different way. Unfortunately, currency conversion is a really complicated thing since exchange rates change frequently and would be inaccurate because we don't know the exchange rate per payment processor. The next iteration of revenue analytics will not require you to bother with even telling us the currency.

We'll close this ticket when the next version of revenue analytics comes out so this issue is easy to find.

**Comment by ericcheungidea** [comment]
For Apple App Store, I think you can get the latest Currency rate set by Apple on its iTunes Connect website

**Comment by sancoLgates** [comment]
i think the currency conversion is too difficult,
what if i just need to change the currency symbol ?

**Comment by Suhail** [comment]
I wanted to update people and just say: we're still committed to making revenue analytics better but we can't provide an ETA and it's likely some time out still.

**Comment by nitiwari-dev** [comment]
Thanks Suhail. Hoping we can get it soon :-)

**Comment by mkou** [comment]
+1

**Comment by pdesantis** [comment]
+1

**Comment by o15a3d4l11s2** [comment]
+1

**Comment by NammariMarkavip** [comment]
+1

**Comment by danrice01** [comment]
+1 the ability to simply change the currency symbol would be a good start.

**Comment by dseelmann** [comment]
+1

**Comment by lucacavallaro** [comment]
+1

**Comment by RitvikM** [comment]
+1 
any update on this?

**Comment by jamesproud** [comment]
+1

**Comment by bjornbos** [comment]
+1

**Comment by ekstro** [comment]
+1

**Comment by kenumir** [comment]
+1

**Comment by brunomac** [comment]
+1 
This is so ridiculous!!! 3 years to implement a requested feature!!! :(
really disappointed with Mixpanel.

**Comment by cannyboy** [comment]
I've noticed that [FB (App Events)](https://developers.facebook.com/docs/app-events/ios) and [Twitter Fabric Answers](https://docs.fabric.io/ios/answers/answers-events.html) provide currency support, and better purchase logging:
````
// FB, obc-C
[FBSDKAppEvents logPurchase:4.32 currency:@"USD"];

// Fabric Answers, swift
Answers.logPurchaseWithPrice(13.50,
                      currency: "USD",
                      success: true,
                      itemName: "Answers Shirt",
                      itemType: "Apparel",
                      itemId: "sku-350",
                      customAttributes: nil)
````

I wouldn't want to speculate why Mixpanel has been so slowwww to get this done, but their latest blog post is about how cannabis startups are the future of tech. Perhaps they are investigating "the opportunities for quantified cannabis" too thoroughly.

**Comment by jbwyme** [comment]
Hahaha while I appreciate cannyboy's theory, it's simply a resource
constraint issue. It's not that we don't think this is valuable or
important, it's just that there are so many things that are valuable and
important that we need to accomplish. Please don't feel ignored by the lack
of response on our end. We just don't really have anything useful to say
other than "it's on the list but not currently lined up for execution".
It's also not as trivial as updating the Mixpanel iOS SDK because we need
to support it in our database and reporting as well. Otherwise it would
already be done. I know this isn't the answer you want to hear but it's the
only one I have. We're actively hiring more mobile and product focused
developers so we can get to more projects like these.

**Comment by Suhail** [comment]
To be totally clear: Right now, we aren't planning on doing this feature for the next 3 months at minimum. We want to make revenue better but, alas, we're resource constrained. We'd rather integrate directly with where you're placing transactions to avoid you having to use the trackCharge API and having to deal with currency conversion.

**Comment by grEvenX** [comment]
@Suhail good to hear you are planning something, the lack of support for this makes revenue tracking useless for a _lot_ of your potential user base. Basicly anyone delivering a app these days operate in different markets. 
It's also a good point that it would be better to get the revenue tracking in some other way, because the current way of handling recurring subscriptions in e.g. iOS makes it hard to track reliably.

**Comment by Suhail** [comment]
Totally hear you. We haven't hit the mark here.

**Comment by sathishc** [comment]
+1

**Comment by kirillsh** [comment]
c'mon guys, firebase analytics has support for that without writing a single line of code.

**Comment by mzekrallah** [comment]
Any update on this guys ? it has been 5 years already ! The revenues part in Mixpanel is meaningless without currency conversions !

**Comment by alekplay** [comment]
You should do it similar to Flurry, at least on iOS. Let users simply pass in the `SKPaymentTransaction` and parse all the data on your end, including currency conversion. They even do receipt validation. Read more here: https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/revenue/ios/

**Comment by zihejia** [comment]
I’m closing this issue because it has been inactive for a few years and we don't have a plan to support it in the near future.
