### ISSUE TITLE
Timed events are missing the `duration` value in the reports

### ISSUE THREAD

**Issue by hirad** [mixpanel/mixpanel-iphone#742]
**Integration Method:** CocoaPods 
**Xcode Version:** 9.0
**Library Version:** 3.1.9
**Platform:** iOS 
**Language:** Objective-C
**Description:** 

When I create reports based on the `duration` value of several timed events, I see that >99% of the duration values are `null`. These are events that I have been tracking with `-timeEvent:` and `-track:` since the very beginning and during testing they definitely did include durations (and some number of events still do).

**Expected Behavior:** 

_ALL_ timed events should have a `duration` value.

**Comment by pchien** [comment]
@hirad sorry for the late response. Do you know if your app will `track` multiple times for one call to `timeEvent`? The way the SDK works only the first `track` call after `timeEvent` with that event name will have `duration`. Subsequent calls won't.

**Comment by hirad** [comment]
@pchien As far as I can tell I'm calling `timeEvent` and `track` properly. During testing I've never seen an event without `duration`. But almost all of them in production don't have `duration` 🤔

**Comment by pchien** [comment]
Could you provide a link (don't worry non-employees won't be able to use the link) to the report on mixpanel.com where you see events without `duration`? This shouldn't be behaving differently between test and production.

**Comment by hirad** [comment]
Here you go: `https://mixpanel.com/report/533049/segmentation/#action:segment,arb_event:'Add%20Record',bool_op:and,chart_analysis_type:linear,chart_type:bar,endpoint:segmentation/numeric,from_date:-29,graph_params:(allow_more_buckets:!f,buckets:12,event:'Add%20Record',from_date:-29,limit:150,on:'properties%5B%22$duration%22%5D',to_date:0,type:general,unit:day),ms_checked:('0%20-%207000':!t,'14000%20-%2021000':!t,'21000%20-%2028000':!t,'28000%20-%2035000':!t,'35000%20-%2042000':!t,'42000%20-%2049000':!t,'49000%20-%2056000':!t,'56000%20-%2063000':!t,'63000%20-%2070000':!t,'7000%20-%2014000':!t,'70000%20-%2077000':!t),ms_values:!('0%20-%207000','7000%20-%2014000','14000%20-%2021000','21000%20-%2028000','28000%20-%2035000','35000%20-%2042000','42000%20-%2049000','49000%20-%2056000','56000%20-%2063000','63000%20-%2070000','70000%20-%2077000'),segfilter:!((dropdown_tab_index:1,property:(name:'$duration',no_second_icon:!t,source:properties,type:number),selected_property_type:number,type:number)),segment_type:number,to_date:0,type:general,unit:day`

**Comment by pchien** [comment]
@hirad I'm not sure why it's happening, but over that time period I'm seeing a little under 2% where `duration` isn't set.
https://mixpanel.com/report/533049/segmentation/#action:segment,arb_event:'Add%20Record',bool_op:and,chart_analysis_type:linear,chart_type:bar,endpoint:segmentation,from_date:-29,graph_params:(event:'Add%20Record',from_date:-29,to_date:0,type:general,unit:day,where:'not%20defined%20(properties%5B%22$duration%22%5D)'),ms_checked:('Add%20Record':!t),ms_values:!('Add%20Record'),segfilter:!((dropdown_tab_index:0,filter:(operand:'',operator:'not%20set'),property:(name:'$duration',source:properties,type:number),selected_property_type:number,type:string)),to_date:0,type:general,unit:day
Maybe you were interpreting everything in the 0-7k block as unset?

**Comment by hirad** [comment]
@pchien That's interesting. I linked you to the wrong report. [This](https://mixpanel.com/report/533049/insights/#~(displayOptions~(chartType~'bar~plotStyle~'standard~analysis~'linear~value~'absolute)~sections~(show~(~(value~(name~'Add*20Record)~resourceType~'events~profileType~null~search~'~math~'total~property~null)~(dataset~'mixpanel~value~(name~'Billing*20Item*20Selection)~resourceType~'events~profileType~null~search~'~math~'total~property~null)~(value~(name~'Diagnoses*20Selection)~resourceType~'all~profileType~null~search~'~math~'total~property~null))~group~(~(dataset~'mixpanel~value~'!duration~resourceType~'events~profileType~'events~search~'~filterType~'string~propertyType~'number~typeCast~'string~unit~null))~time~(~(unit~'day~value~30)))~title~'Sample*20Report*20-*20Comparing*20Duration)) is what made me suspicious that durations were not being captured. That report was prepared by a Mixpanel support member, so maybe i don't really understand it.

**Comment by pchien** [comment]
@hirad that report is comparing frequencies of individual numbers, so `1.034` and `1` have been bucketed differently. Then it's only displaying the top 24 by frequency; `null` is the most frequent overall. However, when we check is or isn't set [like so](https://mixpanel.com/report/533049/insights/#~(displayOptions~(chartType~'bar~plotStyle~'standard~analysis~'linear~value~'absolute)~sections~(show~(~(value~(name~'Add*20Record)~resourceType~'events~profileType~null~search~'~math~'total~property~null)~(dataset~'mixpanel~value~(name~'Billing*20Item*20Selection)~resourceType~'events~profileType~null~search~'~math~'total~property~null)~(value~(name~'Diagnoses*20Selection)~resourceType~'all~profileType~null~search~'~math~'total~property~null))~group~(~(dataset~'mixpanel~value~'!duration~resourceType~'events~profileType~'events~search~'~filterType~'string~propertyType~'number~typeCast~'boolean~unit~null))~time~(~(unit~'day~value~30)))~title~'Sample*20Report*20-*20Comparing*20Duration)), you can see it's almost always set. Also since it's only missing on exactly one instance for the other two events, I suspect it not being set is something in your implementation rather than the Mixpanel library.

**Comment by hirad** [comment]
@pchien _That_ makes a lot of sense. I had not understood that. I wish the support staff could explain it that way - I had a lengthy discussion with them. Now it all makes sense. Thanks for your help @pchien!
