### ISSUE TITLE
MPTweakValue() does not support NSInteger

### ISSUE THREAD

**Issue by jmartini** [mixpanel/mixpanel-iphone#752]
**Integration Method:** CocoaPods
**Xcode Version:** Version 9.1 (9B55)
**Library Version:** 3.2
**Platform:** iOS
**Language:** Objective-C
**Description:**
The header file comment for ```MPTweakValue``` states support for ```NSInteger```:

> Supported types include: BOOL, NSInteger, NSUInteger, CGFloat, NSString *, char *.

The following code creates a compile time error:
```
NSInteger value = MPTweakValue(@"test", (NSInteger)0);
```
> Incompatible pointer to integer conversion initializing 'NSInteger' (aka 'long') with an expression of type 'const char * _Nullable'

 
**Expected Behavior:** 
NSInteger can be used as a tweak value or comment is updated with support of NSInteger removed

**Comment by pchien** [comment]
Ah. Taking a glance at [this](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/MPTweakInlineInternal.h#L68-L102) I think `NSInteger` might not actually be supported by the internal data store. It looks like it'll work if you cast outside `MPTweakValue` instead of casting the 0 inside, though at that point it might make sense to use `int` or `long long` instead. Does that work for you @jmartini?

**Comment by jmartini** [comment]
Yup, I ended up just using ```int``` and that works fine but the produced errors were not obvious (this specified issue is a simplified version of my use case to show the underlying issue). Would be good to update the documentation to reduce confusion for the next person.

**Comment by pchien** [comment]
Got it. I updated those docs on master. Thanks @jmartini!
