### ISSUE TITLE
[Manual install: can't submit app] Unsupported Architecture [x86_64, i386] (can't validate for iTunes) latest framework

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mixpanel/mixpanel-iphone#819]
**Integration Method:**  Manual
**Xcode Version:** 10.1 (10B61)
**Library Version:** 3.3.7
**Platform:** iOS
**Language:**  Objective-C
**Description:** can't submit app] Unsupported Architecture [x86_64, i386]
**Expected Behavior:** ability to submit app to the App Store.

I just dropped latest framework from https://github.com/mixpanel/mixpanel-iphone/releases
to my app and then Archive it and tried to sent to the App Store.
Here is what I got instead: 

![screen shot](https://user-images.githubusercontent.com/3391456/50117234-13d96200-0255-11e9-8e3b-6a5fe8d67d91.png)

----
**XCode 10 no longer supports fat frameworks.**
----

**Comment by zihejia** [comment]
Hi @KAMIKAZEUA, does the script work for you?

**Comment by zihejia** [comment]
Reopen for documentation.

**Comment by KAMIKAZEUA** [comment]
@zihejia I'm not using script for now, because I just run my game into production phase.
I just downloaded & compiled mixpanel framework by removing that architectures. 
Now I can't take risk and test some scripts. 
For me solution is download framework and rebuild it with proper architectures. 
I just looking for a verified fix from mixpanel guys.

**Comment by zihejia** [comment]
@KAMIKAZEUA thanks for the reply. The script was verified by us but it is not an ideal way to integrate Mixpanel. 

We actually not recommend downloading the binary framework directly because of the issue apple has that requires to take an extra hacky step, and it is also hard for version controlling of Mixpanel. 

If you follow our official guide, integration with CocoaPods, Carthage or manual installation with source code, it won't take more effort and it should work. If any problem for above methods, please let us know.

For integration with the binary directly, you can follow the blog from Daniel Kennett(thanks!), http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/. Again, it's being verified working but still not the best. After some consideration, we won't put it into our official guide, hope you understand.

**Comment by KAMIKAZEUA** [comment]
> If you follow our official guide, integration with CocoaPods, Carthage or manual installation with source code, it won't take more effort and it should work. If any problem for above methods, please let us know.

Exactly. 
I did: 
1) https://developer.mixpanel.com/docs/ios :

![screen shot](https://user-images.githubusercontent.com/3391456/51629697-efa62a80-1f50-11e9-906f-eaa673cfc55e.png)

So I downloaded latest framework `Mixpanel.framework.zip` 
 from `releases`.

As I understand now that words: 
 > You can also get the library by downloading the latest version from GitHub and copying it into your project.

Sounds like copy `Mixpanel.framework` into you project, because it's usual way to integrate frameworks. Like I just copy pasted before all other SDK's for my game. 

I don't like and will not be coping whole project into my Xcode project. I really don't like sub-projects.
