### ISSUE TITLE
Fails App Store uploading due to 2 ITMS errors

### ISSUE THREAD

**Issue by mobileben** [mixpanel/mixpanel-iphone#855]
**Integration Method:** CocoaPods / Carthage / Manual
Manual

**Xcode Version:** 
10.2.1

**Library Version:** 
3.4.7 (https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.7)
I am using the pre-builts.

**Platform:** iOS / App Extension / watchOS / tvOS
iOS

**Language:** Swift / Objective-C
Obj-C

**Description:** 
Uploading to App Store resulted in

ERROR ITMS-90209: "Invalid Segment Alignment."
ERROR ITMS-90080: The executable 'Payload/App.app/Frameworks/Mixpanel.frameswork' is not a Position Independent Executable

**Expected Behavior:** 
AppStore submission doesn't reject submission due to MixPanel

**Comment by zihejia** [comment]
Hi @mobileben , thanks for raising it. It's strange, we never had this issue before.  Frameworks can not have the PIE flag since it’s for main executables only(the embedded frameworks built don't have the PIE flag regardless of what build setting was used). Sounds like a bug on the validation side in iTunes Connect. 

some similar issues:
https://github.com/CocoaPods/CocoaPods/issues/5453
https://stackoverflow.com/questions/37607821/xcode-says-some-of-my-pods-are-not-pies-is-this-fine

**Comment by zihejia** [comment]
I'm closing this issue for now since it's not directly related to Mixpanel. Please feel free to reopen it if the problem still exists.
